name: Documentation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install mkdocs mkdocs-material mkdocstrings[python] pymdown-extensions
      
      - name: Build documentation
        run: mkdocs build --strict --verbose
      
      - name: Check documentation build
        run: |
          echo "✓ Documentation built successfully"
          echo "Note: Documentation is hosted on ReadTheDocs at https://metdatapy.readthedocs.io/"
          ls -la site/

